<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_jobs"
 *
 * Auto generated by Extension Builder 2018-08-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Jobs',
    'description' => 'Jobverwaltung',
    'category' => 'plugin',
    'author' => 'Benjamin Riezler',
    'author_email' => 'b.riezler@pixel-ink.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
